server:  
  port: ${PORT:8899}
  
spring:
  profiles:
     active: native
  application:
    name: config-server
#  cloud:
#      config:
#         server:
#            native:
#               search-locations: classpath:/config