spring:  
  application:
    name: client-service
  config:
    import: "optional:configserver:"
#    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: myusername
      password: mypassword
     